### PR TITLE
Final Milestone: Layout main elements in the website using bootstrap

### PR DESCRIPTION
**Pull request by AhmedTohamy01**
This project is about Laying out the basic structure of Newsweek home page and appropriately positioning the elements by using the appropriate Bootstrap classes. This Includes:

- Adding The Navbar.
- Adding Left Sidebar including all contents
- Adding the Right Sidebar including all contents.
- Adding The Magazine Section including all contents.
- Adding Editor Pick Section including all contents.
- Adding Other News Section including all contents.
- Adding Subscription Section including all contents.
- Adding Footer Section including all contents.

**All had been positioned using BootStrap Grid Classes.**

### CODE REVIEW

**Comment by uryelah** [comment]
Hello **Ahmed Tohamy**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all congratulations! Your project looks amazing! 🌟**

There are a couple of minor issues you need to fix before going to the next project, but I'm sure it will be super easy for you considering the quality of your work. 💪 

---------     

## Required Changes 🏗 👷‍♀ 

- [ ] Since this project is about using Boostrap to it's fullest [check this cheat list ](https://hackerthemes.com/bootstrap-cheatsheet/)to see what you can add with Bootstrap classes, instead of normal CSS properties. For example, things like flex or center align can be done with Boostrap.

- [ ] Remember to follow [commit writing best practices ](https://chris.beams.io/posts/git-commit/)from now on:
  - Write your commit messages using the imperative tense
  - Capitalize your commit messages

- [ ] For the images that have text over them, like the images below, for example, you should not use screenshots. Use the elements positioning to add actual text tags over the images.
Screenshot_2020-04-29 Newsweek CLone(1)
Screenshot_2020-04-29 Newsweek CLone

-----

- [ ] You should use the actual 'Newsweek' logo, not text with a similar font, for the navbar and footer.
You can easily find the svg code/image for the real logo by inspecting the page. 
If you are not sure how to use svg images on web development read this great [CSS tricks article.](https://css-tricks.com/using-svg/)

----

- [ ] Please add the little square images/icons to the left of each section header:
Screenshot_2020-04-29 Newsweek(1)

-----

- [ ] The 'In the Magazine' first article image is taller than the following ones. Compare below how your clone looks and how it looks in the original and make it look the same:
Screenshot_2020-04-29 Newsweek CLone(3)
Screenshot_2020-04-29 Newsweek(2)

----

- [ ] Remember to keep using semantic HTML. Use `section` tags for sections and `article` tags for articles. You can [read this if you need a refresher on semantic HTML.](https://www.w3schools.com/html/html5_semantic_elements.asp)


- [ ] Make sure the navbar is fixed to the top like on the original page. You should be able to see it while scrolling down the page.
----

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by AhmedTohamy01** [comment]
Hi Sarah,

Thank you so much for your review, You are professional as usual!

My reply for your comments below:

**- For Point 1:**
With Full Respect to your opinion ,  the project is about using Bootstrap generally, nothing specific, we are NOT Expected to use each and every option in Bootstrap, the project is to measure our ability to link Bootstrap to our HTML file, and start using "some" of the classes which we "might" need to do the job in faster and easier way. This is the actual need of Bootstrap.

The only specific thing we should use Bootstrap in As per Odin Project is the following point:
**_Lay out the basic structure of the page using empty semantic HTML elements that are appropriately sized and which are positioned by using the appropriate Bootstrap classes._**

**And i already did it!**

**- For Point 3, 4, 5, 6 & 8:**

It's all NOT a core requirement of the project, 

as per Odin Project  
_**"don't  get lost in details, it's okay if it's NOT exact."**_

and as per Odin Project also

**_"As usual, ignore any ads, icons, and interactive elements (which use Javascript). If you really want to grab icons, try taking a screenshot of them and making an image file out of that."_**

This is an "Educational Project" we are not supposed to focus on details which waste more time, we should focus on the main core purpose of the project.  Commercial or production projects are different where we should pay attention to tiny details.
The project is to measure our ability to link bootstarp and use some positioning classes from bootstrap. **and as you said your self "Your project looks amazing! " .**

**- For point 2:**
I Will remember.

**- For point 7:**
I already fixed it.

I think after this clarification , all DONE, just need the approval :)

**Comment by uryelah** [comment]
Hey Ahmed, in this specif project Pathwright asks you to make the page as close as possible to the original. 
[Please read the Specifications again here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/65938290/), they can a bit different than the ones just in Odin project, and check the screencap from Pathwright below:

Screenshot_2020-04-29 Microverse Main Curriculum

**Comment by AhmedTohamy01** [comment]
It's already looks exactly like the source page Sarah, But we are cloning live website , the content changes !

"Exactly" means the main elements, the number of elements, the colors .... the whole layout! 

If we apply "exactly" word on everything so you will ask me to change the articles titles and articles content also to match the original website. Or change the article places because it doesn't match the original website which changes dynamically!

Look at the page, it's really like the source page!
It doesn't make sense to reject a project because i'm not using a specific icon or because the photo in the original website is different. 

We are cloning a live website, again, content changes!  
any by the way may be it changes also based on the country you access from!

**Comment by uryelah** [comment]
Hello Ahmed,
All the points made in the last review were about the layout, not the content of the page.

Kindly make a new code review request, I already submitted my last one as 'Changes required'.

**Comment by AhmedTohamy01** [comment]
Thank you Sarah, I already did all the core requirements in the project. 

If i follow each and every comment from you the next TSE will come with different comments and it will be endless cycle! 

The review process should focus on the main requirement of the project, NOT "Hunting Differentiates" !
I have a history with TSEs who apologize for me before when i told them that this is

**Comment by AhmedTohamy01** [comment]
This is your own submission for the same Project Sarah (which already get approved).

https://raw.githack.com/uryelah/Using-Bootstrap/news/index.html

Do you find it matching Newsweek website "Exactly" ?

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Comment by AhmedTohamy01** [comment]
Hi Mike, @mikenath223 

Thank you so much, appreciate your rapid response.

For my comments , of course i didn't mean anything personal. i totally respect all TSEs (Specially Sarah @uryelah ) , and as you saw in the comments i started with a greeting to the previous TSE .

it was just a clear **"_short way"_** to show my point of view regarding the "_**Exactly**_" Word. 

If i will say it in another way , i will say to the TSE  **_"Just apply your rules (that you are applying it now on the student) on your own submission for the same project "._** I Think this is Fair Enough :)

**Pull request merged**
